version: "3.9"
services:
  server:
    build:  ./server
    ports: 
    - "5002:5000"
    volumes: 
    - ./server:/app
    environment: 
      FLASK_ENV: development
      DATABASE_URL: ${DATABASE_URL}
      DATABASE_NAME: ${DATABASE_NAME}
      DATABASE_USER: ${DATABASE_USER}
      DATABASE_PASSWORD: ${DATABASE_PASSWORD}
      
  web:
    build: ./client
    ports: 
      - "3000:3000"
    volumes: 
      - ./client:/user/src/app
    depends_on: 
      - server