import React from "react";


const Surpise = ({ generateFeelings }) => {
    
    const surpriseFeelings = [
        "Surprise",
        "Shock",
        "Amazement",
        "Astonishment",
        "Wonder",
        "Dismay",
        "Stun",
        "Startle",
        "Bewilderment",
        "Confusion",
        "Unpredictability",
        "Astoundment",
        "Marvel",
        "Disbelief",
        "Jolt",
        "Stupefaction",
        "Wondrous",
        "Blow",
        "Unforeseen",
        "Fascination",
        "Awe",
        "Stagger",
        "Flabbergast",
        "Bolt",
        "Impress",
        "Wowed",
        "Incredulity",
        "Thrill",
        "Stupefy",
        "Boggle",
        "Startling",
        "Appalled",
        "Wham",
        "Nonplussed",
        "Eye-opener",
        "Enthrall",
        "Eureka",
        "Disconcert",
        "Enchanted",
        "Dazzled",
        "Unanticipated",
        "Discombobulate",
        "Amazed",
        "Astounding",
        "Overwhelmed",
        "Astound",
        "Dumbfound",
        "Baffled",
        "Mind-boggling",
        "Mind-blowing",
        "Wonderstruck",
        "Incredulous",
        "Jolted",
        "Flummoxed",
        "Startled",
        "Gobsmacked",
        "Shell-shocked",
        "Perplexed",
        "Thunderstruck",
        "Stunned",
        "Blindsided",
        "Taken aback",
        "Speechless",
        "Dumbstruck",
        "Agog",
        "Astonished",
        "Dazed",
        "Awestruck",
        "Overawed",
        "Flabbergasted",
        "Dumbfounded",
        "Awe-struck",
        "Mazed",
        "Stupefied",
        "Bewildered",
        "Boggled",
        "Mystified",
        "Out of the blue",
        "Unbelievable",
        "Marvelous",
        "Unexpectedly",
        "Eye-popping",
        "Awe-inspiring",
        "Unforeseeable",
        "Miraculous",
        "Serendipitous",
        "Spontaneous",
        "Unplanned",
        "Sudden",
        "Striking",
        "Phenomenal",
        "Spectacular",
        "Extraordinary",
        "Sensational",
        "Astonishingly",
        "Inconceivable",
        "Startlingly",
        "Incredible",
        "Unimaginable"
    ];
    
    
    
    
    return (
        <>
            {generateFeelings(surpriseFeelings)}
        </>
    )
}

export default Surpise;